export const countries = [
    "United States",
    "Canada",
    "United Kingdom",
    "Australia",
    "Germany",
    "France",
    "Italy",
    "Spain",
    "Japan",
    "China",
    "India",
    "Brazil",
    "Mexico",
    "Argentina",
    "Netherlands",
    "Sweden",
    "Norway",
    "Denmark",
    "Switzerland",
    "Austria",
    "Belgium",
    "Portugal",
    "Greece",
    "Ireland",
    "New Zealand",
    "Singapore",
    "South Korea",
    "Thailand",
    "Vietnam",
    "Indonesia",
    "Malaysia",
    "Philippines",
    "UAE",
    "Saudi Arabia",
    "South Africa",
    "Egypt",
    "Turkey",
    "Russia",
    "Poland",
    "Czech Republic",
    "Hungary",
    "Romania",
    "Croatia",
    "Iceland",
    "Finland"
];